<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var eluhr\shop\models\Order $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="order-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Order',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute id -->
			<?= $form->field($model, 'id')->textInput(['maxlength' => true]) ?>

<!-- attribute first_name -->
			<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

<!-- attribute surname -->
			<?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

<!-- attribute email -->
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<!-- attribute street_name -->
			<?= $form->field($model, 'street_name')->textInput(['maxlength' => true]) ?>

<!-- attribute house_number -->
			<?= $form->field($model, 'house_number')->textInput(['maxlength' => true]) ?>

<!-- attribute postal -->
			<?= $form->field($model, 'postal')->textInput(['maxlength' => true]) ?>

<!-- attribute city -->
			<?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>

<!-- attribute type -->
			<?=                         $form->field($model, 'type')->dropDownList(
                            eluhr\shop\models\Order::optstype()
                        ); ?>

<!-- attribute is_executed -->
			<?= $form->field($model, 'is_executed')->textInput() ?>

<!-- attribute discount_code_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'discount_code_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(eluhr\shop\models\DiscountCode::find()->all(), 'id', 'label'),
    [
        'prompt' => Yii::t('shop', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['discount_code_id'])),
    ]
); ?>

<!-- attribute info_mail_has_been_sent -->
			<?= $form->field($model, 'info_mail_has_been_sent')->textInput() ?>

<!-- attribute has_different_delivery_address -->
			<?= $form->field($model, 'has_different_delivery_address')->textInput() ?>

<!-- attribute paid -->
			<?= $form->field($model, 'paid')->textInput() ?>

<!-- attribute date_of_birth -->
			<?= $form->field($model, 'date_of_birth')->textInput() ?>

<!-- attribute created_at -->

<!-- attribute updated_at -->

<!-- attribute internal_notes -->
			<?= $form->field($model, 'internal_notes')->textarea(['rows' => 6]) ?>

<!-- attribute customer_details -->
			<?= $form->field($model, 'customer_details')->textarea(['rows' => 6]) ?>

<!-- attribute status -->
			<?=                         $form->field($model, 'status')->dropDownList(
                            eluhr\shop\models\Order::optsstatus()
                        ); ?>

<!-- attribute shipping_price -->
			<?= $form->field($model, 'shipping_price')->textInput(['maxlength' => true]) ?>

<!-- attribute paypal_id -->
			<?= $form->field($model, 'paypal_id')->textInput(['maxlength' => true]) ?>

<!-- attribute paypal_token -->
			<?= $form->field($model, 'paypal_token')->textInput(['maxlength' => true]) ?>

<!-- attribute paypal_payer_id -->
			<?= $form->field($model, 'paypal_payer_id')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_first_name -->
			<?= $form->field($model, 'delivery_first_name')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_surname -->
			<?= $form->field($model, 'delivery_surname')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_street_name -->
			<?= $form->field($model, 'delivery_street_name')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_house_number -->
			<?= $form->field($model, 'delivery_house_number')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_postal -->
			<?= $form->field($model, 'delivery_postal')->textInput(['maxlength' => true]) ?>

<!-- attribute delivery_city -->
			<?= $form->field($model, 'delivery_city')->textInput(['maxlength' => true]) ?>

<!-- attribute shipment_link -->
			<?= $form->field($model, 'shipment_link')->textInput(['maxlength' => true]) ?>

<!-- attribute invoice_number -->
			<?= $form->field($model, 'invoice_number')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('shop', 'Order'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('shop', 'Create') : Yii::t('shop', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

