<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var eluhr\shop\models\Order $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('shop', 'Order');
$this->params['breadcrumbs'][] = ['label' => Yii::t('shop', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('shop', 'View');
?>
<div class="giiant-crud order-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('shop', 'Order') ?>
        <small>
            <?= Html::encode($model->id) ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
    '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('shop', 'Edit'),
    [ 'update', 'id' => $model->id],
    ['class' => 'btn btn-info']
) ?>

            <?= Html::a(
    '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('shop', 'Copy'),
    ['create', 'id' => $model->id, 'Order'=>$copyParams],
    ['class' => 'btn btn-success']
) ?>

            <?= Html::a(
    '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('shop', 'New'),
    ['create'],
    ['class' => 'btn btn-success']
) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . Yii::t('shop', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('eluhr\shop\models\Order'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'id',
        'first_name',
        'surname',
        'email:email',
        'street_name',
        'house_number',
        'postal',
        'city',
        'is_executed',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'discount_code_id',
    'value' => ($model->discountCode ?
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['/shop/crud/discount-code/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->discountCode->label, ['/shop/crud/discount-code/view', 'id' => $model->discountCode->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Order'=>['discount_code_id' => $model->discount_code_id]])
        :
        '<span class="label label-warning">?</span>'),
],
        'info_mail_has_been_sent',
        'has_different_delivery_address',
        'paid',
        'date_of_birth',
        'created_at',
        'updated_at',
        'internal_notes:ntext',
            [
                'attribute'=>'status',
                'value'=>eluhr\shop\models\Order::getStatusValueLabel($model->status),
            ],
            [
                'attribute'=>'type',
                'value'=>eluhr\shop\models\Order::getTypeValueLabel($model->type),
            ],
        'shipping_price',
        'paypal_id',
        'paypal_token',
        'paypal_payer_id',
        'delivery_first_name',
        'delivery_surname',
        'delivery_street_name',
        'delivery_house_number',
        'delivery_postal',
        'delivery_city',
        'shipment_link',
        'invoice_number',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a(
        '<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('shop', 'Delete'),
        ['delete', 'id' => $model->id],
        [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . Yii::t('shop', 'Are you sure to delete this item?') . '',
    'data-method' => 'post',
    ]
    ); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('Variants'); ?>
<div style='position: relative'>
<div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
        '<span class="glyphicon glyphicon-list"></span> ' . Yii::t('shop', 'List All') . ' Variants',
        ['/shop/crud/variant/index'],
        ['class'=>'btn text-muted btn-xs']
    ) ?>
  <?= Html::a(
        '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('shop', 'New') . ' Variant',
        ['/shop/crud/variant/create', 'Variant' => ['id' => $model->id]],
        ['class'=>'btn btn-success btn-xs']
    ); ?>
  <?= Html::a(
        '<span class="glyphicon glyphicon-link"></span> ' . Yii::t('shop', 'Attach') . ' Variant',
        ['/shop/crud/order-item/create', 'OrderItem'=>['order_id'=>$model->id]],
        ['class'=>'btn btn-info btn-xs']
    ) ?>
</div>
</div>
<?php Pjax::begin(['id'=>'pjax-Variants', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Variants ul.pagination a, th a']) ?>
<?=
 '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getOrderItems(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-orderitems',
        ]
    ]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => Yii::t('shop', 'First'),
        'lastPageLabel'  => Yii::t('shop', 'Last')
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {delete}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = '/shop/crud/order-item' . '/' . $action;
        $params['OrderItem'] = ['order_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        'delete' => function ($url, $model) {
            return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                    'class' => 'text-danger',
                    'title'         => Yii::t('shop', 'Remove'),
                    'data-confirm'  => Yii::t('shop', 'Are you sure you want to delete the related item?'),
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ]);
        },
'view' => function ($url, $model) {
    return Html::a(
        '<span class="glyphicon glyphicon-cog"></span>',
        $url,
        [
                        'data-title'  => Yii::t('shop', 'View Pivot Record'),
                        'data-toggle' => 'tooltip',
                        'data-pjax'   => '0',
                        'class'       => 'text-muted',
                    ]
    );
},
    ],
    'controller' => '/shop/crud/order-item'
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'variant_id',
    'value' => function ($model) {
        if ($rel = $model->variant) {
            return Html::a($rel->label, ['/shop/crud/variant/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'name',
        'quantity',
        'single_price',
        'created_at',
        'updated_at',
]
])
 . '</div>'
?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
    [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
    'content' => $this->blocks['eluhr\shop\models\Order'],
    'active'  => true,
],
[
    'content' => $this->blocks['Variants'],
    'label'   => '<small>Variants <span class="badge badge-default">'. $model->getVariants()->count() . '</span></small>',
    'active'  => false,
],
 ]
                 ]
);
    ?>
</div>
