<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\models\base;

use Yii;

/**
 * This is the base-model class for table "sp_discount_code".
 *
 * @property integer $id
 * @property string $code
 * @property string $percent
 * @property string $expiration_date
 * @property integer $used
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \eluhr\shop\models\Order[] $orders
 * @property string $aliasModel
 */
abstract class DiscountCode extends \eluhr\shop\models\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sp_discount_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'percent', 'expiration_date'], 'required'],
            [['percent'], 'number'],
            [['expiration_date', 'created_at', 'updated_at'], 'safe'],
            [['used'], 'integer'],
            [['code'], 'string', 'max' => 128],
            [['code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('shop', 'ID'),
            'code' => Yii::t('shop', 'Code'),
            'percent' => Yii::t('shop', 'Percent'),
            'expiration_date' => Yii::t('shop', 'Expiration Date'),
            'used' => Yii::t('shop', 'Used'),
            'created_at' => Yii::t('shop', 'Created At'),
            'updated_at' => Yii::t('shop', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(\eluhr\shop\models\Order::className(), ['discount_code_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\shop\models\query\DiscountCodeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\shop\models\query\DiscountCodeQuery(get_called_class());
    }
}
