<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\models\base;

use Yii;

/**
 * This is the base-model class for table "sp_email_template".
 *
 * @property string $name
 * @property string $template
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class EmailTemplate extends \eluhr\shop\models\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sp_email_template';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['template'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('shop', 'Name'),
            'template' => Yii::t('shop', 'Template'),
            'created_at' => Yii::t('shop', 'Created At'),
            'updated_at' => Yii::t('shop', 'Updated At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\shop\models\query\EmailTemplateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\shop\models\query\EmailTemplateQuery(get_called_class());
    }
}
