<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\models\base;

use Yii;

/**
 * This is the base-model class for table "sp_filter".
 *
 * @property integer $id
 * @property string $name
 * @property integer $rank
 * @property string $presentation
 * @property string $created_at
 * @property string $updated_at
 * @property integer $is_online
 *
 * @property \eluhr\shop\models\TagXFilter[] $tagXFilters
 * @property \eluhr\shop\models\Tag[] $tags
 * @property string $aliasModel
 */
abstract class Filter extends \eluhr\shop\models\ActiveRecord
{



    /**
    * ENUM field values
    */
    const PRESENTATION_DROPDOWN = 'dropdown';
    const PRESENTATION_RADIOS = 'radios';
    public $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sp_filter';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['rank', 'is_online'], 'integer'],
            [['presentation'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 80],
            [['name'], 'unique'],
            ['presentation', 'in', 'range' => [
                    self::PRESENTATION_DROPDOWN,
                    self::PRESENTATION_RADIOS,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('shop', 'ID'),
            'name' => Yii::t('shop', 'Name'),
            'rank' => Yii::t('shop', 'Rank'),
            'presentation' => Yii::t('shop', 'Presentation'),
            'created_at' => Yii::t('shop', 'Created At'),
            'updated_at' => Yii::t('shop', 'Updated At'),
            'is_online' => Yii::t('shop', 'Is Online'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagXFilters()
    {
        return $this->hasMany(\eluhr\shop\models\TagXFilter::className(), ['facet_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(\eluhr\shop\models\Tag::className(), ['id' => 'tag_id'])->viaTable('sp_tag_x_filter', ['facet_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\shop\models\query\FilterQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\shop\models\query\FilterQuery(get_called_class());
    }


    /**
     * get column presentation enum value label
     * @param string $value
     * @return string
     */
    public static function getPresentationValueLabel($value)
    {
        $labels = self::optsPresentation();
        if (isset($labels[$value])) {
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column presentation ENUM value labels
     * @return array
     */
    public static function optsPresentation()
    {
        return [
            self::PRESENTATION_DROPDOWN => Yii::t('shop', self::PRESENTATION_DROPDOWN),
            self::PRESENTATION_RADIOS => Yii::t('shop', self::PRESENTATION_RADIOS),
        ];
    }
}
