<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\models\base;

use Yii;

/**
 * This is the base-model class for table "sp_order_item".
 *
 * @property string $order_id
 * @property integer $variant_id
 * @property string $configuration_id
 * @property string $name
 * @property integer $quantity
 * @property string $extra_info
 * @property string $single_price
 * @property string $single_net_price
 * @property string $vat
 * @property string $created_at
 * @property string $updated_at
 * @property string $configuration_json
 *
 * @property \eluhr\shop\models\Configuration $configuration
 * @property \eluhr\shop\models\Order $order
 * @property \eluhr\shop\models\Variant $variant
 * @property string $aliasModel
 */
abstract class OrderItem extends \eluhr\shop\models\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sp_order_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'variant_id', 'name', 'quantity', 'extra_info', 'single_price'], 'required'],
            [['variant_id', 'quantity'], 'integer'],
            [['single_price', 'single_net_price', 'vat'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['configuration_json'], 'string'],
            [['order_id', 'configuration_id'], 'string', 'max' => 36],
            [['name', 'extra_info'], 'string', 'max' => 128],
            [['order_id', 'variant_id', 'extra_info'], 'unique', 'targetAttribute' => ['order_id', 'variant_id', 'extra_info']],
            [['configuration_id'], 'exist', 'skipOnError' => true, 'targetClass' => \eluhr\shop\models\Configuration::className(), 'targetAttribute' => ['configuration_id' => 'id']],
            [['order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \eluhr\shop\models\Order::className(), 'targetAttribute' => ['order_id' => 'id']],
            [['variant_id'], 'exist', 'skipOnError' => true, 'targetClass' => \eluhr\shop\models\Variant::className(), 'targetAttribute' => ['variant_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'order_id' => Yii::t('shop', 'Order ID'),
            'variant_id' => Yii::t('shop', 'Variant ID'),
            'configuration_id' => Yii::t('shop', 'Configuration ID'),
            'name' => Yii::t('shop', 'Name'),
            'quantity' => Yii::t('shop', 'Quantity'),
            'extra_info' => Yii::t('shop', 'Extra Info'),
            'single_price' => Yii::t('shop', 'Single Price'),
            'single_net_price' => Yii::t('shop', 'Single Net Price'),
            'vat' => Yii::t('shop', 'Vat'),
            'created_at' => Yii::t('shop', 'Created At'),
            'updated_at' => Yii::t('shop', 'Updated At'),
            'configuration_json' => Yii::t('shop', 'Configuration Json'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConfiguration()
    {
        return $this->hasOne(\eluhr\shop\models\Configuration::className(), ['id' => 'configuration_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(\eluhr\shop\models\Order::className(), ['id' => 'order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVariant()
    {
        return $this->hasOne(\eluhr\shop\models\Variant::className(), ['id' => 'variant_id']);
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\shop\models\query\OrderItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\shop\models\query\OrderItemQuery(get_called_class());
    }


}
