<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\models\base;

use Yii;

/**
 * This is the base-model class for table "sp_tag".
 *
 * @property integer $id
 * @property numeric $value
 * @property string $desc
 * @property string $created_at
 * @property string $updated_at
 *
 * @property string $aliasModel
 */
abstract class Vat extends \eluhr\shop\models\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sp_vat';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['value'], 'number'],
            [['value'], 'required'],
            [['value'], 'unique'],
            [['desc'], 'string', 'max' => 255],
            [['created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('shop', 'ID'),
            'value' => Yii::t('shop', 'Vat value'),
            'desc' => Yii::t('shop', 'Description'),
            'created_at' => Yii::t('shop', 'Created At'),
            'updated_at' => Yii::t('shop', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVariants()
    {
        return $this->hasMany(\eluhr\shop\models\Variant::className(), ['id' => 'vat_id']);
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\shop\models\query\VatQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\shop\models\query\VatQuery(get_called_class());
    }


}
