<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var eluhr\shop\models\OrderItem $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="order-item-form">

    <?php $form = ActiveForm::begin(
    [
    'id' => 'OrderItem',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
);
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute order_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'order_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(eluhr\shop\models\Order::find()->all(), 'id', 'id'),
    [
        'prompt' => Yii::t('shop', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['order_id'])),
    ]
); ?>

<!-- attribute variant_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'variant_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(eluhr\shop\models\Variant::find()->all(), 'id', 'label'),
    [
        'prompt' => Yii::t('shop', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['variant_id'])),
    ]
); ?>

<!-- attribute name -->
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute quantity -->
			<?= $form->field($model, 'quantity')->textInput() ?>

<!-- attribute single_price -->
			<?= $form->field($model, 'single_price')->textInput(['maxlength' => true]) ?>

<!-- attribute created_at -->

<!-- attribute updated_at -->
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
        [
                    'encodeLabels' => false,
                    'items' => [
                        [
    'label'   => Yii::t('shop', 'OrderItem'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('shop', 'Create') : Yii::t('shop', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
    );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

