<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\shop\controllers\crud\base;

use eluhr\shop\models\TagXProduct;
    use eluhr\shop\models\search\TagXProduct as TagXProductSearch;
use eluhr\shop\controllers\crud\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* TagXProductController implements the CRUD actions for TagXProduct model.
*/
class TagXProductController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all TagXProduct models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new TagXProductSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single TagXProduct model.
* @param integer $tag_id
	 * @param integer $product_id
*
* @return mixed
*/
public function actionView($tag_id, $product_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($tag_id, $product_id),
]);
}

/**
* Creates a new TagXProduct model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new TagXProduct;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'tag_id' => $model->tag_id, 'product_id' => $model->product_id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing TagXProduct model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $tag_id
	 * @param integer $product_id
* @return mixed
*/
public function actionUpdate($tag_id, $product_id)
{
$model = $this->findModel($tag_id, $product_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing TagXProduct model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $tag_id
	 * @param integer $product_id
* @return mixed
*/
public function actionDelete($tag_id, $product_id)
{
try {
$this->findModel($tag_id, $product_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$tag_id, $product_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the TagXProduct model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $tag_id
	 * @param integer $product_id
* @return TagXProduct the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($tag_id, $product_id)
{
if (($model = TagXProduct::findOne(['tag_id' => $tag_id, 'product_id' => $product_id])) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
