<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var eluhr\shop\models\TagXProduct $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="tag-x-product-form">

    <?php $form = ActiveForm::begin([
    'id' => 'TagXProduct',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute tag_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'tag_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(eluhr\shop\models\Tag::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('shop', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['tag_id'])),
    ]
); ?>

<!-- attribute product_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'product_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(eluhr\shop\models\Product::find()->all(), 'id', 'title'),
    [
        'prompt' => Yii::t('shop', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['product_id'])),
    ]
); ?>

<!-- attribute created_at -->

<!-- attribute updated_at -->
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('shop', 'TagXProduct'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('shop', 'Create') : Yii::t('shop', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

